[phases.setup]
nixPkgs = ["nodejs_20"]
nixOverlays = []

[phases.install]
cmds = ["npm ci --no-audit --no-fund --no-cache"]
cacheDirectories = []

[phases.build]
cmds = ["npm run build"]
cacheDirectories = []

[start]
cmd = "npm run start"
