[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci --no-audit --no-fund"]
cacheDirectories = []

[phases.build]
cmds = ["npm run build"]
cacheDirectories = []

[start]
cmd = "npx next start -H 0.0.0.0 -p $PORT"
